USE TECUMG ;

CREATE INDEX idx_autores_nacionalidad ON AUTORES(NACIONALIDAD);
CREATE TABLE AUTORES (
    ID_AUTOR INT PRIMARY KEY IDENTITY,
    NOMBRE VARCHAR(100) NOT NULL,
    NACIONALIDAD VARCHAR(50)
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY IDENTITY,
    DESCRIPCION VARCHAR(50) NOT NULL
);

CREATE TABLE EDITORIALES (
    ID_EDITORIAL INT PRIMARY KEY IDENTITY,
    NOMBRE VARCHAR(50) NOT NULL,
    PAIS VARCHAR(50)
);

CREATE INDEX idx_libros_categoria ON LIBROS(ID_CATEGORIA);
CREATE TABLE LIBROS (
    ID_LIBRO INT PRIMARY KEY IDENTITY,
    TITULO VARCHAR(100) NOT NULL,
    ID_AUTOR INT FOREIGN KEY REFERENCES AUTORES(ID_AUTOR),
    ID_CATEGORIA INT FOREIGN KEY REFERENCES CATEGORIA(ID_CATEGORIA),
    ID_EDITORIAL INT FOREIGN KEY REFERENCES EDITORIALES(ID_EDITORIAL),
    FECHA_PUBLICACION DATE NOT NULL
);

CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY IDENTITY,
    NOMBRE VARCHAR(50) NOT NULL,
    CORREO VARCHAR(50),
    DIRECCION VARCHAR(100),
    TELEFONO VARCHAR(20)
);

CREATE INDEX idx_prestamos_fecha_prestamo ON PRESTAMOS(FECHA_PRESTAMO);
CREATE TABLE PRESTAMOS (
    ID_PRESTAMO INT PRIMARY KEY IDENTITY,
    ID_LIBRO INT FOREIGN KEY REFERENCES LIBROS(ID_LIBRO),
    ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID_USUARIO),
    FECHA_PRESTAMO DATE NOT NULL,
    FECHA_DEVOLUCION DATE NULL
);


-- Insertar Datos
INSERT INTO AUTORES (NOMBRE, NACIONALIDAD)
VALUES ('Homero', 'Griega'), ('Virgilio', 'Romana'), ('Cervantes', 'Español');

INSERT INTO CATEGORIA (DESCRIPCION)
VALUES ('Comedia'), ('Suspenso'), ('Literatura Griega');

INSERT INTO EDITORIALES (NOMBRE, PAIS)
VALUES ('Editorial Planeta', 'España'), ('Editorial Random', 'México');

INSERT INTO LIBROS (TITULO, ID_AUTOR, ID_CATEGORIA, ID_EDITORIAL, FECHA_PUBLICACION)
VALUES ('La Odisea', 1, 3, 2, '2018-03-20'), ('La Eneida', 2, 3, 1, '2017-04-12');

INSERT INTO USUARIOS (NOMBRE, CORREO, DIRECCION, TELEFONO)
VALUES ('Juan Pérez', 'juan@example.com', 'Calle Falsa 123', '123456789');

INSERT INTO PRESTAMOS (ID_LIBRO, ID_USUARIO, FECHA_PRESTAMO)
VALUES (1, 1, '2019-11-05'), (2, 1, '2018-11-15');


--Consultas SQL
--Consulta de libros prestados en noviembre de 2017, 2018 y 2019, ordenados por tipo de libro (categoría):
SELECT L.TITULO, P.FECHA_PRESTAMO, C.DESCRIPCION AS TIPO_LIBRO
FROM PRESTAMOS P
JOIN LIBROS L ON P.ID_LIBRO = L.ID_LIBRO
JOIN CATEGORIA C ON L.ID_CATEGORIA = C.ID_CATEGORIA
WHERE MONTH(P.FECHA_PRESTAMO) = 11
AND YEAR(P.FECHA_PRESTAMO) IN (2017, 2018, 2019)
ORDER BY C.DESCRIPCION;

--Consulta de veces que se ha prestado un libro de categoría 'Suspenso' en los últimos 6 años, ordenado por tipo de libro:
SELECT L.TITULO, COUNT(P.ID_PRESTAMO) AS VECES_PRESTADO, C.DESCRIPCION AS TIPO_LIBRO
FROM PRESTAMOS P
JOIN LIBROS L ON P.ID_LIBRO = L.ID_LIBRO
JOIN CATEGORIA C ON L.ID_CATEGORIA = C.ID_CATEGORIA
WHERE C.DESCRIPCION = 'Suspenso'
AND P.FECHA_PRESTAMO >= DATEADD(YEAR, -6, GETDATE())
GROUP BY L.TITULO, C.DESCRIPCION
ORDER BY C.DESCRIPCION;

--Consulta de préstamos de libros cuyos autores no sean españoles, argentinos ni alemanes, ordenado por autor de manera ascendente:
SELECT L.TITULO, A.NOMBRE AS AUTOR, A.NACIONALIDAD
FROM PRESTAMOS P
JOIN LIBROS L ON P.ID_LIBRO = L.ID_LIBRO
JOIN AUTORES A ON L.ID_AUTOR = A.ID_AUTOR
WHERE A.NACIONALIDAD NOT IN ('Español', 'Argentino', 'Alemán')
ORDER BY A.NOMBRE ASC;

--Consulta de libros de literatura griega prestados por cada usuario, ordenado por usuario de manera descendente:
SELECT U.NOMBRE, L.TITULO, C.DESCRIPCION AS CATEGORIA
FROM PRESTAMOS P
JOIN LIBROS L ON P.ID_LIBRO = L.ID_LIBRO
JOIN USUARIOS U ON P.ID_USUARIO = U.ID_USUARIO
JOIN CATEGORIA C ON L.ID_CATEGORIA = C.ID_CATEGORIA
WHERE C.DESCRIPCION = 'Literatura Griega'
ORDER BY U.NOMBRE DESC;

--Consulta del número de libros cuyos autores son de literatura romana, su editorial es española y la categoría es comedia,
--ordenado por editorial de manera descendente:
SELECT COUNT(L.ID_LIBRO) AS NUMERO_LIBROS, E.NOMBRE AS EDITORIAL, A.NACIONALIDAD, C.DESCRIPCION AS CATEGORIA
FROM LIBROS L
JOIN AUTORES A ON L.ID_AUTOR = A.ID_AUTOR
JOIN EDITORIALES E ON L.ID_EDITORIAL = E.ID_EDITORIAL
JOIN CATEGORIA C ON L.ID_CATEGORIA = C.ID_CATEGORIA
WHERE A.NACIONALIDAD = 'Romana'
AND E.PAIS = 'España'
AND C.DESCRIPCION = 'Comedia'
GROUP BY E.NOMBRE, A.NACIONALIDAD, C.DESCRIPCION
ORDER BY E.NOMBRE DESC;
