USE RINCONGT;

DROP TABLE VENTA;

SELECT * FROM CLIENTE;

SELECT * FROM DETALLE_FACTURA2;

CREATE TABLE VENTA (
    ID_VENTA INT IDENTITY(1,1) PRIMARY KEY,
    FECHA DATETIME NOT NULL,
    TOTAL_FACTURA DECIMAL(10, 2) NOT NULL, -- Sin restricción de clave foránea para este campo
    ID_FACTURA INT FOREIGN KEY REFERENCES FACTURA(ID_FACTURA),
    ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE(ID_CLIENTE),
    ID_DEVOLUCION INT FOREIGN KEY REFERENCES DEVOLUCION(ID_DEVOLUCION)
);

-- Para ver las columnas de la tabla VENTA
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'VENTA';

-- Para ver las columnas de la tabla PRODUCTO
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PRODUCTO';

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DEVOLUCION';

SELECT TOP 10 *
FROM DEVOLUCION;



ALTER TABLE CLIENTE
ADD FECHA_REGISTRO DATE NOT NULL DEFAULT GETDATE();

IF OBJECT_ID('spAgregarCliente', 'P') IS NOT NULL
BEGIN
    DROP PROCEDURE spAgregarCliente;
END

CREATE PROCEDURE spAgregarCliente
    @NOMBRE VARCHAR(50),
    @TELEFONO VARCHAR(50),
    @DIRECCION VARCHAR(50),
    @NIT VARCHAR(50) = NULL,  -- Si NIT es opcional
    @FECHA_REGISTRO DATE
AS
BEGIN
    INSERT INTO CLIENTE (NOMBRE, TELEFONO, DIRECCION, NIT, FECHA_REGISTRO)
    VALUES (@NOMBRE, @TELEFONO, @DIRECCION, @NIT, @FECHA_REGISTRO);
END
